import React from 'react';
import Head from 'next/head'
import Image from 'next/image'
import Footer from '../components/Footer/Footer'
import HeroSection from '../components/Homepage/HeroSection'
import TrendingSection from '../components/Homepage/TrendingSection'
import Navbar from '../components/Navbar/Navbar';
import styles from '../styles/Home.module.css'
import InfoSection from '../components/Homepage/InfoSection';
import ProductSection from '../components/Homepage/ProductSection';
import Banner from '../components/Homepage/Banner';
import TestimonySection from '../components/Homepage/TestimonySection';
import PolicySection from '../components/Homepage/PolicySection';
import NewsletterSection from '../components/Homepage/NewsletterSection';
import withBaseLayout from '../components/Layout/BaseLayout';

const Home=()=> {
  return (
    <React.Fragment>
      <Head>
        <title>Miss Valentine</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

        <HeroSection />
        <TrendingSection />
        <InfoSection />
        <ProductSection />
        <Banner />
        <TestimonySection />
        <PolicySection />
    </React.Fragment>
  )
}

const HOCprops ={
  displayName : "Home",
  fixedNavbar: false,
};
export default withBaseLayout(Home, HOCprops); 
